### ISSUE TITLE
Doesn't work with pip 1.1

### ISSUE THREAD

**Issue by denplis** [playpauseandstop/bootstrapper#14]
<p>pip 1.1 haven't pip.__version__ attr.</p>

<pre><code>
Traceback (most recent call last):
  File "/usr/local/bin/bootstrapper", line 9, in <module>
    load_entry_point('bootstrapper==0.5', 'console_scripts', 'bootstrapper')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources.py", line 345, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources.py", line 2381, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources.py", line 2087, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/bootstrapper.py", line 69, in <module>
    } if int(pip.__version__.split('.')[0]) < 6 else {},
AttributeError: 'module' object has no attribute '__version__'
</code></pre>
